### ISSUE TITLE
Truffle Deploy fails in Truffle 4

### ISSUE THREAD

**Issue by jcrain** [Arachnid/subdomain-registrar#21]
Running `truffle deploy` gives this error:

```
truffle deploy
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Error: Exceeds block gas limit
    at StateManager.queueTransaction (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:83114:21)
    at GethApiDouble.eth_sendTransaction (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:82631:14)
    at GethApiDouble.handleRequest (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:82434:10)
    at next (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:52153:18)
    at VmSubprovider.handleRequest (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:59291:12)
    at next (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:52153:18)
    at GethDefaults.handleRequest (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:82339:12)
    at next (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:52153:18)
    at FilterSubprovider.handleRequest (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:58850:7)
    at next (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:52153:18)
    at Object.InvalidResponse (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
    at /Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:331156:36
    at /Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:175492:11
    at /Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:314196:9
    at XMLHttpRequest.request.onreadystatechange (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
    at XMLHttpRequest._setReadyState (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
    at IncomingMessage.<anonymous> (/Users/jcrain/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:70564:24)
    at emitNone (events.js:110:20)
```

I'm running these versions of truffle & solidity
Truffle v4.0.1 (core: 4.0.1)
Solidity v0.4.18 (solc-js)

**Comment by Arachnid** [comment]
What version of testrpc are you using? It's working fine here with v4.1.3 (ganache-core: 1.1.3). Does `truffle test` work?

**Comment by Arachnid** [comment]
Oh, you're using 4.0.1. I haven't tried it on Truffle 4 yet; it's possible that there's a breaking change there.

**Comment by decanus** [comment]
This should now work as we have updated to truffle 4
